vdiManager/adAuth/urls.py
from django.urls import path
from .views import adauth_get_info,adauth_list_info,license_info

app_name = 'adAuth'
urlpatterns = [
    path('',adauth_get_info , name='getinfo'),
    path('license/',license_info , name='licenseinfo'),
    path('authinfo/',adauth_list_info , name='listinfo'),

]

vdiManager/vdiManager/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vdiApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('adAuth.urls')),
    path('captcha',include("captcha.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vdiManager/adAuth/models.py
from django.db import models

# Create your models here.

vdiManager/adAuth/forms.py
from django import forms
from captcha.fields import CaptchaField, CaptchaTextInput

class CaptchaLoginForm(forms.Form):
   username = forms.CharField(max_length=65)
   password = forms.CharField(max_length=65, widget=forms.PasswordInput)
   ad_auth = forms.CharField(required=False,widget=forms.CheckboxInput,label='ldap authentication:')
   captcha=CaptchaField(widget=CaptchaTextInput(attrs={'class': 'form-control'}),label='Please enter the characters in the image')
   

vdiManager/adAuth/views.py
from django.shortcuts import render,HttpResponse,redirect
from vdiApp.models import VirtualDesktop, UserProfile
from django.db.models import Q
from django.contrib import messages
from vdiApp.util import *
from vdiManager.settings import Config
from .forms import CaptchaLoginForm
from datetime import datetime
import re

def license_info(request):
    context={'info':'test'}
    return render(request,'adAuth/license.html',context=context)

# Create your views here.
def adauth_get_info(request):

    if status_check() == False:
        return redirect('/license')
    form = CaptchaLoginForm()
    context ={'captcha_form': form}
    return render(request, 'adAuth/login.html',context=context)

def create_vdi():
    pass



    

def adauth_list_info(request):
    if request.method == 'POST':
        form = CaptchaLoginForm(request.POST)
        if form.is_valid():      
            ip_pattern = re.compile(r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})')      
            username = request.POST['username']
            password = request.POST['password']
            if 'ad_auth' in request.POST:
                Active_Directory_Enabled = True
            else:
                request.POST.get('ad_auth',False)

                Active_Directory_Enabled = False

            
            
            try:
                ##### Local Authentication#################
                if Active_Directory_Enabled == False:
                    owner = get_profile_or_None(user=username,password=password)
                    print("DEBUG",owner)
                    if owner == None:
                        print("Owner not found")
                        messages.add_message(request,messages.ERROR,'username or password is incorrect')
                        return redirect('/')
                    #### Profile is active
                    elif owner != None and owner.owner_is_active and owner.owner_create_by_ldap == False:
                        owner_vd = get_vd_or_None(container_user=username,is_activate=True)
                        print(owner_vd)
                        
                        #### VDI is active
                        if owner_vd != None:
                            if owner_vd.vd_is_activate == True:

                                print("active VD",owner_vd.vd_owner.owner_server)

                                vdi_name=f"{owner_vd.vd_container_name}"
                                vdi_url=f"{owner_vd.vd_owner.owner_server.server_scheme}://{owner_vd.vd_owner.owner_server.server_hostname}/{username}/"
                                vdi_vncpass=f"{owner_vd.vd_container_vncpass}"
                                vdi_browser_url=f"{owner_vd.vd_owner.owner_server.server_scheme}://{owner_vd.vd_owner.owner_server.server_hostname}/{username}/browser"
                                vdi_browser_user=f"{username}"
                                vdi_browser_pass=f"{owner_vd.vd_browser_pass}"
                                vdi_created_at= owner_vd.vd_created_at
                                vdi_expired_at= owner_vd.vd_expired_at

                                context ={
                                    'vdi_name':f"{vdi_name}",
                                    'vdi_url': f"{vdi_url}",
                                    'vdi_vncpass':f"{vdi_vncpass}",
                                    'vdi_browser_url':f"{vdi_browser_url}",
                                    'vdi_browser_user':f"{vdi_browser_user}",
                                    'vdi_browser_pass':f"{vdi_browser_pass}",
                                    'vdi_created_at':f"{vdi_created_at}",
                                    'vdi_expired_at':f"{vdi_expired_at}",
                                }
                                return render(request, 'adAuth/info.html',context=context)
                 
                        #### create VDI
                        else:
                            
                            vdi_name = f"{username}-vdi"
                            browser_name = f"{username}-filebrowser"
                            vnc_pass = gen_password()
                            
                            creator_ip = get_client_ip(request)
                            print("DEBUG THIS:",vdi_name,browser_name,vnc_pass,creator_ip)
                            # server = get_server()
                            server = owner.owner_server
                            print("VDI")
                            
                            container = create_container(server,image=f"{Config.DOCKER_DESKTOP_IMAGE}"
                                                        ,name=f"{vdi_name}"
                                                        ,cpu='2'
                                                        ,mem='2g'
                                                        ,volumes={f"{server.data_path}/{vdi_name}/Downloads": {'bind': f"/home/{username}/Downloads", 'mode': 'rw'}}
                                                        ,env={"USER":f"{username}","PASSWORD":f"{password}aqr","VNC_PASSWORD":f"{vnc_pass}","RELATIVE_URL_ROOT":f"{username}","HTTP_PROXY":f"{username}:{password}@172.20.0.2:3128","HTTPS_PROXY":f"{username}:{password}@172.20.0.2:3128"}
                                                        ,network='no-internet'
                                                        ,ip=f"{owner.owner_ip}"
                                                        )
                            print(container['result'])
                            if int(container['result']) == 1:
                                vdi_id = container['container_spec']['id']
                                vdi_shortid = container['container_spec']['shortid']
                                fb_password = gen_password()
                                fb_container = create_container(server,image=f"{Config.DOCKER_BROWSER_IMAGE}"
                                                        ,name=f"{browser_name}"
                                                        ,cpu='1'
                                                        ,mem='1g'
                                                        ,volumes={f"{server.data_path}/{vdi_name}/Downloads": {'bind': f"/srv", 'mode': 'ro'}}
                                                        ,env={"FBUSER":f"{username}","FBPASSWORD":f"{fb_password}","BASEURL":f"/{username}/fbrowser"}
                                                        ,network='no-internet'
                                                        ,ip=f"{owner.owner_browser_ip}"
                                                        )
                                print(fb_container)
                                if int(fb_container['result']) == 1:
                                    try:
                                        owner.owner_vd_created_number += 1
                                        owner.save() 
                                        vdi_model = VirtualDesktop.objects.create(vd_container_name=f"{vdi_name}",
                                                                                vd_container_cpu='2',
                                                                                vd_container_mem='2g',
                                                                                vd_container_img=Config.DOCKER_DESKTOP_IMAGE,
                                                                                vd_container_id=f"{vdi_id}",
                                                                                vd_container_shortid=f"{vdi_shortid}",
                                                                                vd_container_user=f"{username}",
                                                                                vd_container_password=f"{password}",
                                                                                vd_container_vncpass=f"{vnc_pass}",
                                                                                vd_browser_pass = f"{fb_password}",
                                                                                vd_owner=owner,
                                                                                vd_description=f"created vdi by local users",
                                                                                vd_browser_id=f"{fb_container['container_spec']['id']}",
                                                                                vd_browser_img=f"{Config.DOCKER_BROWSER_IMAGE}",
                                                                                vd_browser_name=f"{browser_name}",
                                                                                vd_is_activate = True,
                                                                                vd_created_by =f"LOCAL-{username}",
                                                                                vd_creator_ip=f"{creator_ip}",
                                                                                vd_expired_at = get_expiry_time()
                                                                                )
                                        vdi_name=f"{vdi_name}"
                                        vdi_url=f"{server.server_scheme}://{server.server_hostname}/{username}/"
                                        vdi_vncpass=f"{vnc_pass}"
                                        vdi_browser_url=f"{server.server_scheme}://{server.server_hostname}/{username}/fbrowser"
                                        vdi_browser_user=f"{owner.owner_user}"
                                        vdi_browser_pass=f"{vdi_model.vd_browser_pass}"
                                        vdi_created_at= vdi_model.vd_created_at
                                        vdi_expired_at= vdi_model.vd_expired_at

                                        context ={

vdiManager/templates/adAuth/adinput.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>ورود</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-sm-center h-100">
				<div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
					<div class="text-center my-5">
						
						<img src="{% static 'assets/img/right-side-image.png' %}" alt="logo" width="100">
					</div>
					<div class="card shadow-lg">
						<div class="card-body p-5">
							<h1 class="fs-4 card-title fw-bold mb-4">Login</h1>
							<form method="POST" action="{% url 'adAuth:listinfo' %}" class="needs-validation" novalidate="" autocomplete="off">
								{% csrf_token %}
								<div class="mb-3">
									<label class="mb-2 text-muted" for="email">Username</label>
									<input id="username" type="text" class="form-control" name="username" value="" required autofocus>
									<div class="invalid-feedback">
										Username is invalid
									</div>
								</div>

								<div class="mb-3">
									<div class="mb-2 w-100">
										<label class="text-muted" for="password">Password</label>
										<!-- <a href="forgot.html" class="float-end">
											Forgot Password?
										</a> -->
									</div>
									<input id="password" type="password" class="form-control" name="password" required>
								    <div class="invalid-feedback">
								    	Password is required
							    	</div>
								</div>

								<div class="d-flex align-items-center">
									<!-- <div class="form-check">
										<input type="checkbox" name="remember" id="remember" class="form-check-input">
										<label for="remember" class="form-check-label">Remember Me</label>
									</div> -->
									<input type="hidden" name="next" value="{{ request.GET.next }}"/>
									<button type="submit" class="btn btn-primary ms-auto">
										Login
									</button>
								</div>
							</form>
						</div>
						<!-- <div class="card-footer py-3 border-0">
							<div class="text-center">
								Don't have an account? <a href="register.html" class="text-dark">Create One</a>
							</div>
						</div> -->
					</div>
					<div class="text-center mt-5 text-muted">
					تمام حقوق این وبگاه متعلق به آستان قدس رضوی است

					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- <script src="{% static 'assets/js/login.js' %}"></script> -->
</body>
</html>

vdiManager/templates/adAuth/auth.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>ورود</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
	<link href="{% static 'assets/css/bootstrap-5.0.0-beta2.min.css' %}" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<style>
	body {
	  background-image: url("{% static 'assets/img/gonbad.jpg' %}");
	}

	#id_captcha_1 {
    max-width: 100px;
    margin-top: 8px;
}
</style> 


<body>
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-sm-center h-100">
				<div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
					<div class="text-center my-5">
						
						<img src="{% static 'assets/img/aqr.png' %}" alt="logo" width="100">
					</div>
					<div class="card shadow-lg">



						<div class="card-body p-5">
							<h1 class="fs-4 card-title fw-bold mb-4">Login</h1>
							<form method="POST" action="{% url 'adAuth:listinfo' %}" class="needs-validation" novalidate="" autocomplete="off">
								{% csrf_token %}
								<div class="mb-3">
									<label class="mb-2 text-muted" for="email">Username</label>
									<input id="username" type="text" class="form-control" name="username" value="" required autofocus>
									<div class="invalid-feedback">
										Username is invalid
									</div>
								</div>

								<div class="mb-3">
									<div class="mb-2 w-100">
										<label class="text-muted" for="password">Password</label>
										<!-- <a href="forgot.html" class="float-end">
											Forgot Password?
										</a> -->
									</div>
									<input id="password" type="password" class="form-control" name="password" required>
								    <div class="invalid-feedback">
								    	Password is required
							    	</div>
								</div>
								<div class="mb-3">
											{{captcha_form.captcha}}
								</div>
								<div class="d-flex align-items-center">
									<!-- <div class="form-check">
										<input type="checkbox" name="remember" id="remember" class="form-check-input">
										<label for="remember" class="form-check-label">Remember Me</label>
									</div> -->
									<input type="hidden" name="next" value="{{ request.GET.next }}"/>

									<button type="submit" class="btn btn-primary ms-auto">
										Login
									</button>
								</div>
							</form>
						</div>
						<!-- <div class="card-footer py-3 border-0">
							<div class="text-center">
								Don't have an account? <a href="register.html" class="text-dark">Create One</a>
							</div>
						</div> -->
					</div>
					<div class="text-center mt-5 text-muted">
					تمام حقوق این وبگاه متعلق به آستان قدس رضوی است

					</div>
					{% if messages %}
					<div class="row">
					<div class="text-center mt-5 text-muted">
						{% for message in messages %}
						<div class="alert alert-{{ message.tags }}" role="alert">
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="True">&times;</span>
						  </button>
							<h1 ><p style="color: rgb(172, 84, 43)">{{ message }}</p></h1>
						</div>
						{% endfor %}
					  </div>
				  
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</section>

	<!-- <script src="{% static 'assets/js/login.js' %}"></script> -->
</body>
</html>

vdiManager/templates/adAuth/info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">


<title>مشخصات  میزکار</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" type="image/png" href="{% static 'vdi.png' %}"/>
<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
<style type="text/css">
    body {
	  background-image: url("{% static 'assets/img/vdi-blue.png' %}");
	}

    .inf-content{
    border:1px solid #DDDDDD;
    -webkit-border-radius:10px;
    -moz-border-radius:10px;
    border-radius:10px;
    box-shadow: 7px 7px 7px rgba(0, 0, 0, 0.3);
    background-color: azure;

}	
.center-screen {
  display: flex;
  justify-content: center;
  align-items: center;
  /* text-align: center; */
  min-height: 100vh;
}		                                                      
    </style>
</head>
<body>
    {{ form.errors }}
    {{ form.non_field_errors }}
<div class="container">
    <!-- <div class="col-md-5">
        <img alt style="width:600px;" title class="img-circle img-thumbnail isTooltip" src="{% static 'assets/img/astan.jpg' %}" data-original-title="Usuario">
        
    </div> -->

    
<div class="panel-body center-screen">
    <div id="tempMessage" style="display: none; padding: 10px; background-color: #52c6bc; color: #fff; position: fixed; top: 0; left: 50%; transform: translateX(-50%);"></div>
<div class="col-md-6 inf-content">
<strong>Information</strong><br>
<div class="table-responsive">
<table class="table table-user-information">
<tbody>
<tr>
<td>
<strong>
<span class="glyphicon glyphicon-phone text-primary"></span>
VDI Name
</strong>
</td>
<td class="text-primary">
{{vdi_name}}
</td>
</tr>
<tr>
<td>
<strong>
<span class="glyphicon glyphicon-link  text-primary"></span>
VDI URL
</strong>
</td>
<td class="text-primary">
<a href="{{vdi_url}}" target="_blank">{{vdi_url}}</a>
</td>
</tr>
<tr>
<td>
<strong>
<span class="glyphicon glyphicon-cloud text-primary"></span>
VDI VNCPass
</strong>
</td>
<td class="text-primary" id="vncpass" onclick="copyText('vncpass')">
{{vdi_vncpass}}
</td>
</tr>
<tr>
<td>
<strong>
<span class="glyphicon glyphicon-link text-primary"></span>
File Manager
</strong>
</td>
<td class="text-primary">
    <a href="{{vdi_browser_url}}" target="_blank">{{vdi_browser_url}}</a>

</td>
</tr>
<tr>
<td>
<strong>
<span class="glyphicon glyphicon-user  text-primary"></span>
File Manager User
</strong>
</td>
<td class="text-primary" id="fbuser" onclick="copyText('fbuser')">
{{vdi_browser_user}}
</td>
</tr>
<tr>
<td>
<strong>
<span class="glyphicon glyphicon-lock text-primary"></span>
File Manager Pass
</strong>
</td>
<td class="text-primary" id="fbpass" onclick="copyText('fbpass')">
{{vdi_browser_pass}}
</td>
</tr>
<tr>
<td>
<strong>
<span class="glyphicon glyphicon-calendar text-primary"></span>
VDI Created
</strong>
</td>
<td class="text-primary">
{{vdi_created_at}}
</td>
</tr>
<tr>
<td>
<strong>
<span class="glyphicon glyphicon-calendar text-primary"></span>
VDI Expired
</strong>
</td>
<td class="text-primary">
{{vdi_expired_at}}
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script type="text/javascript">	
</script>
<script src="{% static 'assets/js/copytext.js'  %}" type="text/javascript"></script>
</body>
</html>

vdiManager/templates/adAuth/license.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>License Expired</title>
    <!-- Bootstrap CSS -->
    <link href="{% static 'assets/css/expirebootstrap.css' %}" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-header bg-danger text-white">
                    <h2>License Expired</h2>
                </div>
                <div class="card-body">
                    <p class="card-text">Your license has expired. Please contact support for renewal.</p>
                    <!-- Add additional information or contact details if needed -->
                </div>
                <div class="card-footer text-muted">
                    <p>&copy; 2023 Your Company Name. All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS and Popper.js -->
<script src="{% static 'assets/css/expire-jquery.js' %}"></script>
<script src="{% static 'assets/css/expire-popper.js' %}"></script>
<script src="{% static 'assets/css/expire-bootstrap.js' %}"></script>

</body>
</html>

vdiManager/templates/adAuth/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>ورود</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'vdi.png' %}"/>
	<link rel="shortcut icon" type="image/png" href="{% static 'vdi.png' %}"/>
	<link href="{% static 'assets/css/bootstrap-5.0.0-beta2.min.css' %}" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<style>
	body {
		margin: 0;
		padding: 0;
		background-image: url("{% static 'assets/img/vdi-blue.png' %}");
		background-repeat: no-repeat;
		background-size: cover;
		background-attachment: fixed;
		width: 100%;
      	height: 100%;
	}

	#id_captcha_1 {
    max-width: 100px;
    margin-top: 8px;
}
</style> 


<body>
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-sm-center h-100">
				<div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
					<div class="text-center my-5">
						
						<img src="{% static 'assets/img/favicon2.ico' %}" alt="logo" width="100">
					</div>
					<div class="card shadow-lg">



						<div class="card-body p-5">
							<h1 class="fs-4 card-title fw-bold mb-4">Login</h1>
							<form method="POST" action="{% url 'adAuth:listinfo' %}" class="needs-validation" novalidate="" autocomplete="off">
								{% csrf_token %}
						
									{{captcha_form.as_p}}
							
					
							
					

									<button type="submit" class="btn btn-primary ms-auto">
										Login
									</button>
								</div>

							</form>
						</div>
						<!-- <div class="card-footer py-3 border-0">
							<div class="text-center">
								Don't have an account? <a href="register.html" class="text-dark">Create One</a>
							</div>
						</div> -->
					</div>
					<!-- <div class="text-center mt-5 text-muted">
					تمام حقوق این وبگاه متعلق به آستان قدس رضوی است

					</div> -->
					{% if messages %}
					<div class="row">
					<div class="text-center mt-5 text-muted">
						{% for message in messages %}
						<div class="alert alert-{{ message.tags }}" role="alert">
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="True">&times;</span>
						  </button>
							<h1 ><p style="color: rgb(172, 84, 43)">{{ message }}</p></h1>
						</div>
						{% endfor %}
					  </div>
				  
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</section>

	<!-- <script src="{% static 'assets/js/login.js' %}"></script> -->
</body>
</html>