vdiManager/adAuth/urls.py
from django.urls import path
from .views import adauth_get_info,adauth_list_info,license_info

app_name = 'adAuth'
urlpatterns = [
    path('',adauth_get_info , name='getinfo'),
    path('license/',license_info , name='licenseinfo'),
    path('authinfo/',adauth_list_info , name='listinfo'),

]

vdiManager/vdiApp/api/v1/urls.py
from django.urls import path
from .views import *
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

app_name = "api-v1"

schema_view = get_schema_view(
   openapi.Info(
      title="VDI API",
      default_version='v1',
      description="VDI Api Document",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns =[
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('desktops', api_vdesktops, name='vdesktops'),
    path('desktops/<id>', api_vdesktops, name='vdesktops'),
    path('profiles', api_profiles, name='profiles'),
    path('profiles/<id>', api_profiles, name='profiless'),
    path('servers', api_servers, name='servers'),
    path('servers/<id>', api_servers, name='servers'),
    path('servers/<id>/check', server_check, name='servers'),
    path('search/<q>', search, name='search'),
]

vdiManager/vdiApp/urls.py
from django.urls import path, include
from .views import *

app_name = 'vdiApp'
urlpatterns = [
    path('dashboard/',dashboard , name='dashboard'),
    path('search/',search , name='search'), 
    path('vdcreate/',vdcreate , name='vdcreate'), 
    path('vdlist/',vdlist , name='vdlist'), 
    path('vdremove/<vd_id>',vdremove , name='vdremove'), 
    path('vdinfo/<info_id>',vdinfo , name='vdinfo'),
    path('serverlist/',serverlist , name='serverlist'),
    path('serverinfo/<info_id>',server_info , name='serverinfo'),
    path('profilecreate/',profile_create , name='profilecreate'),
    path('profilelist/',profile_list , name='profilelist'),
    path('profileinfo/<info_id>',profile_info , name='profileinfo'),
    path('profileremove/<profile_id>',profile_remove , name='profileremove'),
    path('profileedit/<profile_id>',profile_edit , name='profileedit'),
    path('profileedit/',profile_edit , name='profileedit'),
    path('api/v1/',include('vdiApp.api.v1.urls')),
]

vdiManager/vdiManager/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vdiApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('adAuth.urls')),
    path('captcha',include("captcha.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vdiManager/vdiApp/forms.py
from django import forms
from .models import VirtualDesktop,UserProfile

cpu_choices =[
    ('2','2 core'),
    ('4','4 core'),
]

mem_choices =[
    ('2g','2GB'),
    ('4g','4GB'),
]

class CreateVirtualDesktop(forms.ModelForm):
    class Meta:
        model = VirtualDesktop
        fields = ['vd_container_name','vd_container_vncpass',
        'vd_owner','vd_letter_number','vd_description'
        ]
    vd_container_cpu = forms.ChoiceField(choices=cpu_choices,label='پردازنده')
    vd_container_mem = forms.ChoiceField(choices=mem_choices,label='حافظه')
 
class CreateProfile(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['owner_name','owner_user','owner_password','owner_server','owner_description','owner_create_by_ldap','owner_is_active']

vdiManager/vdiApp/api/v1/views.py
from rest_framework.decorators import api_view,authentication_classes,permission_classes
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from rest_framework.pagination import PageNumberPagination
from django.db.models import Q
from .serializers import VDISerializer,VDIPostSerializer,ServerSerializer,ProfileSerializer
from ...models import VirtualDesktop,VDIServer,UserProfile
from vdiManager.settings import Config
from django.forms.models import model_to_dict
from ...util import api_check,get_client_ip, update_nginx, get_server, jwt_gen_token, server_status,create_container,gen_password, get_free_ip,get_profile_or_None,get_vd_or_None,get_expiry_time,profile_update_password,getUsersInGroup

from django.shortcuts import get_object_or_404

@api_view(['GET','POST','DELETE'])
@authentication_classes([SessionAuthentication, BasicAuthentication])
@permission_classes([IsAuthenticated])
def api_vdesktops(request,id=None):
    if api_check() == False:
        return Response({"error":"Your License is Not Valid"},status=status.HTTP_401_UNAUTHORIZED)
    paginator = PageNumberPagination()
    paginator.page_size = 10
    if request.method == 'GET' and id==None:
        try:
            vds = VirtualDesktop.objects.all()
            print(vds)
            result_page = paginator.paginate_queryset(vds, request)
            serializer = VDISerializer(result_page,many=True)
            # print(get_client_ip(request))
            return Response(serializer.data)
        except VirtualDesktop.DoesNotExist:
            return Response({"detaile":"Not Found"},status=status.HTTP_404_NOT_FOUND)    
    elif request.method == 'GET' and id != None:
        vd = get_object_or_404(VirtualDesktop, pk=id)
        serializer = VDISerializer(vd)
        return Response(serializer.data)
    elif request.method == 'POST':
        mydata = request.data
        password = request.data['vd_container_password']
        username = request.data['vd_container_user']
        is_ldap = request.data['is_ldap']
        profile  = get_profile_or_None(user=username,password=password)
        server = get_server()
        vdi_name = f"{username}-vdi"
        browser_name = f"{username}-filebrowser"
        vnc_pass = gen_password()
        creator_ip = get_client_ip(request)
        container_ip = get_free_ip(server=server)
        if is_ldap == False:
            if profile == None:
                return Response({"detaile":"Not Found"},status=status.HTTP_404_NOT_FOUND)
            elif profile != None and profile.owner_is_active and profile.owner_create_by_ldap == False:
                vd = get_vd_or_None(container_user=username,is_activate=True)
                if vd != None :
                    serializer = VDIPostSerializer(data=vd)
                    return Response(serializer.data)
                else:
                    container = create_container(server,image=f"{Config.DOCKER_DESKTOP_IMAGE}"
                                                ,name=f"{vdi_name}"
                                                ,cpu='2'
                                                ,mem='2g'
                                                ,volumes={f"{server.data_path}/{vdi_name}/Downloads": {'bind': f"/home/{mydata['vd_container_user']}/Downloads", 'mode': 'rw'}}
                                                ,env={"USER":f"{mydata['vd_container_user']}","PASSWORD":f"{password}aqr","VNC_PASSWORD":f"{vnc_pass}","RELATIVE_URL_ROOT":f"{mydata['vd_container_user']}","HTTP_PROXY":f"{mydata['vd_container_user']}:{password}@172.20.0.2:3128","HTTPS_PROXY":f"{mydata['vd_container_user']}:{password}@172.20.0.2:3128"}
                                                ,network='no-internet'
                                                ,ip=container_ip
                                                )
                    if int(container['result']) == 1:
                        vdi_id = container['container_spec']['id']
                        vdi_shortid = container['container_spec']['shortid']
                        fb_password = gen_password()
                        fb_container = create_container(server,image=f"{Config.DOCKER_BROWSER_IMAGE}"
                                                ,name=f"{browser_name}"
                                                ,cpu='1'
                                                ,mem='1g'
                                                ,volumes={f"{server.data_path}/{vdi_name}/Downloads": {'bind': f"/srv", 'mode': 'ro'}}
                                                ,env={"FBUSER":f"{mydata['vd_container_user']}","FBPASSWORD":f"{fb_password}","BASEURL":f"/{mydata['vd_container_user']}/fbrowser"}
                                                ,network='no-internet'
                                                ,ip=f"{profile.owner_browser_ip}"
                                                )
                        if int(fb_container['result']) == 1:
                            try:
                                vd_data = {
                                    'vd_container_name' :f"{vdi_name}",
                                    'vd_container_cpu' :'2',
                                    'vd_container_mem':'2g',
                                    'vd_container_img': f"{Config.DOCKER_DESKTOP_IMAGE}",
                                    'vd_container_id' :f"{vdi_id}",
                                    'vd_container_shortid' :f"{vdi_shortid}",
                                    'vd_container_user' :f"{username}",
                                    'vd_container_password' : f"{password}",
                                    'vd_container_vncpass' : f"{vnc_pass}",
                                    'vd_browser_pass' : f"{fb_password}",
                                    'vd_owner' : f"{profile.pk}",
                                    'vd_description' : f"created vdi by local users",
                                    'vd_browser_id' : f"{fb_container['container_spec']['id']}",
                                    'vd_browser_img' : f"{Config.DOCKER_BROWSER_IMAGE}",
                                    'vd_browser_name' :f"{browser_name}",
                                    'vd_is_activate' : True,
                                    'vd_created_by' : f"LOCAL-{username}",
                                    'vd_creator_ip' : f"{creator_ip}",
                                    'vd_expired_at' : f"{get_expiry_time()}"
                                }
                                nginx_result = update_nginx(server=server,user=f"{username}",vd_container=f"{vdi_name}",fb_container=f"{browser_name}")
                                if int(nginx_result['result']) == 1:
                                    serializer = VDIPostSerializer(data=vd_data)
                                    serializer.is_valid(raise_exception=True)
                                    serializer.save()
                                    return Response(serializer.data)
                            except Exception as e:
                                return Response({"detaile":f"{e}"},status=status.HTTP_404_NOT_FOUND)
        else:
            ldap_user = getUsersInGroup(server_ip=f"{Config.Active_Directory_ServerIP}",username= username, password= password,domain=Config.Active_Directory_DomainName,group=Config.Active_Directory_GroupName)

            if ldap_user[0] == False:
                return Response({"detaile":"Not Found"},status=status.HTTP_401_UNAUTHORIZED)
            else:
                profile = get_object_or_404(UserProfile, owner_user=username)
                profile_update_password(username=username,password=password)
                profile = get_profile_or_None(user=username,password=password)
                if profile != None and profile.owner_is_active and profile.owner_create_by_ldap == True:
                    vd = get_vd_or_None(container_user=username,is_activate=True)
                    if vd != None :
                        serializer = VDIPostSerializer(data=vd)
                        return Response(serializer.data)
                    else:
                        container = create_container(server,image=f"{Config.DOCKER_DESKTOP_IMAGE}"
                                                    ,name=f"{vdi_name}"
                                                    ,cpu='2'
                                                    ,mem='2g'
                                                    ,volumes={f"{server.data_path}/{vdi_name}/Downloads": {'bind': f"/home/{mydata['vd_container_user']}/Downloads", 'mode': 'rw'}}
                                                    ,env={"USER":f"{mydata['vd_container_user']}","PASSWORD":f"{password}aqr","VNC_PASSWORD":f"{vnc_pass}","RELATIVE_URL_ROOT":f"{mydata['vd_container_user']}","HTTP_PROXY":f"{mydata['vd_container_user']}:{password}@172.20.0.2:3128","HTTPS_PROXY":f"{mydata['vd_container_user']}:{password}@172.20.0.2:3128"}
                                                    ,network='no-internet'
                                                    ,ip=container_ip
                                                    )
                        if int(container['result']) == 1:
                            vdi_id = container['container_spec']['id']
                            vdi_shortid = container['container_spec']['shortid']
                            fb_password = gen_password()
                            fb_container = create_container(server,image=f"{Config.DOCKER_BROWSER_IMAGE}"
                                                    ,name=f"{browser_name}"
                                                    ,cpu='1'
                                                    ,mem='1g'

vdiManager/templates/vdiApp/profilecreate.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block contentwraper %}
<h1 class="m-0 text-dark">ایجاد پروفایل</h1>
{% endblock%}

{% block maincontent %}
  <!-- Content Wrapper. Contains page content -->
  {% if messages %}
  <div class="row">
  <div class="col-sm-6 col-sm-offset-3">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
          <h1 ><p style="color: blue">{{ message }}</p></h1>
      </div>
      {% endfor %}
    </div>

  </div>
{% endif %}
    <section class="content">
      <div class="container-fluid">


          <form action="{% url 'vdiApp:profilecreate' %}" method="post">
            {% csrf_token %}
            
            <div class="row ">
                {{ form|bootstrap }}
            </div> 
    <p>{{v}}</p>
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">ایجاد پروفایل</button>
  </form>

  
{% endblock %}

vdiManager/templates/vdiApp/profileeditlist.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}

{% block contentwraper %}
<h1 class="m-0 text-dark">لیست ویرایش پروفایل ها</h1>
{% endblock%}

{% block maincontent %}

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">نام پروفایل</th>
        <th scope="col">فعال</th>
        <th scope="col">کاربری</th>
        <th scope="col">پسورد</th>
        <th scope="col">تعداد ساخته شده </th>
        <th scope="col">آیپی کانتینر</th>
        <th scope="col">آیپی فایل منیجر</th>
        <th scope="col">تاریخ ایجاد</th>
      </tr>
    </thead>
    <tbody>
      {% for profile in profiles%}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'vdiApp:profileedit' profile_id=profile.owner_user %}">{{ profile.owner_name }}</a></td>
        <td>
          {%if profile.owner_is_active %}
               <img src="{% static 'assets/img/icon-yes.svg' %}" alt="{{ cert.cert_is_activate }}">
          {%else%}
               <img src="{% static 'assets/img/icon-no.svg' %}" alt="{{ cert.cert_is_activate }}">
          {%endif%}
        </td>
        <td>{{ profile.owner_user }}</td>
        <td>{{ profile.owner_password }}</td>
        <td>{{ profile.owner_vd_created_number}}</td>
        <td>{{ profile.owner_ip}}</td>
        <td>{{ profile.owner_browser_ip}}</td>

        <td>{{ profile.owner_created_at|to_jalali:'%Y/%m/%d' }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="text-xs-center">
<nav aria-label="Page navigation example">
<!-- 
      <span class="current">
        Page {{ certs.number }} of {{ certs.paginator.num_pages }}.
      </span> -->

   <ul class="pagination justify-content-center">
      <li class="page-item">
          {% if profiles.has_previous %}
          <a class="page-link" aria-label="Previous" href="?page={{ profiles.previous_page_number }}">previous</a>
          {% endif %}
          <span class="sr-only">Previous</span>
        
      </li>
      {% for i in profiles.paginator.page_range%}
          {%if profiles.number == i %}
          <li class="page-item active"><a class="page-link " href="?page={{i}}">{{i}}</a></li>
          {%else%}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {%endif%}
      {%endfor%}
      <li class="page-item">
          {% if profiles.has_next %}
          <a class="page-link" aria-label="Next" href="?page={{ profiles.next_page_number }}">next</a>
          {% endif %}
          <span class="sr-only">Next</span>
       
      </li>
    </ul> 
</nav>
</div>
{% endblock %}

vdiManager/templates/vdiApp/profileinfo.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}
{% block contentwraper %}
<!-- <h1 class="m-0 text-dark">مشخصات پروفایل</h1>
<hr> -->
{% endblock%}

{% block maincontent %}
<div class="content-wraper">
    {% if messages %}
    <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="True">&times;</span>
          </button>
            <h1 ><p style="color: blue">{{ message }}</p></h1>
        </div>
        {% endfor %}
      </div>
  
    </div>
  {% endif %}

  <div class="panel-body center-screen">

    <div class="col-md-6 inf-content">
    <strong>مشخصات پروفایل</strong><br>
    <div class="table-responsive">
    <table class="table table-user-information">
    <tbody>
    <tr>
    <td>
    <strong>
    <span class="glyphicon glyphicon-phone text-primary"></span>
    نام
    </strong>
    </td>
    <td class="text-primary">
      {{profile.owner_name }}
    </td>
    </tr>
    <tr>
    <td>
    <strong>
    <span class="glyphicon glyphicon-link  text-primary"></span>
    کاربری(username)
    </strong>
    </td>
    <td class="text-primary">
      {{profile.owner_user}}
    </td>
    </tr>
    <tr>
    <td>
    <strong>
    <span class="glyphicon glyphicon-cloud text-primary"></span>
    رمز عبور
    </strong>
    </td>
    <td class="text-primary">
      {{profile.owner_password }}
    </td>
    </tr>
    <tr>
    <td>
    <strong>
    <span class="glyphicon glyphicon-link text-primary"></span>
    آیپی میزکار
    </strong>
    </td>
    <td class="text-primary">
      {{profile.owner_ip }}
    </td>
    </tr>
    <tr>
    <td>
    <strong>
    <span class="glyphicon glyphicon-user  text-primary"></span>
    آیپی مدیریت فایل
    </strong>
    </td>
    <td class="text-primary">
      {{profile.owner_browser_ip}}
    </td>
    </tr>
    <tr>
    <td>
    <strong>
    <span class="glyphicon glyphicon-lock text-primary"></span>
    تعداد ساخته شده
    </strong>
    </td>
    <td class="text-primary">
      {{profile.owner_vd_created_number}}
    </td>
    </tr>
    <tr>
    <td>
    <strong>
    <span class="glyphicon glyphicon-calendar text-primary"></span>
    سرور
    </strong>
    </td>
    <td class="text-primary">
      {{profile.owner_server}}
    </td>
    </tr>
    <tr>
    <td>
    <strong>
    <span class="glyphicon glyphicon-calendar text-primary"></span>
    LDAP
    </strong>
    </td>
    <td class="text-primary">
      {%if profile.owner_create_by_ldap %}
      <img src="{% static 'assets/img/icon-yes.svg' %}" alt="{{ cert.cert_is_activate }}">
      {%else%}
      <img src="{% static 'assets/img/icon-no.svg' %}" alt="{{ cert.cert_is_activate }}">
      {%endif%}

    </td>
    </tr>
    <tr>
      <td>
      <strong>
      <span class="glyphicon glyphicon-calendar text-primary"></span>
      فعال
      </strong>
      </td>
      <td class="text-primary">
        {%if profile.owner_is_active %}
        <img src="{% static 'assets/img/icon-yes.svg' %}" alt="{{ cert.cert_is_activate }}">
        {%else%}
        <img src="{% static 'assets/img/icon-no.svg' %}" alt="{{ cert.cert_is_activate }}">
        {%endif%}
      
      </td>
      </tr>
      <tr>
        <td>
        <strong>
        <span class="glyphicon glyphicon-calendar text-primary"></span>
        پسورد VNC
        </strong>
        </td>
        <td class="text-primary" id="vncpass" onclick="copyText('vncpass')">
          {{vd_vnc_pass}}
        </td>
        </tr>
        <tr>
          <td>
          <strong>
          <span class="glyphicon glyphicon-calendar text-primary"></span>
          توضیحات
          </strong>
          </td>
          <td class="text-primary">
            {{profile.owner_description }}
          </td>
          </tr>
          <tr>
            <td>
            <strong>
            <span class="glyphicon glyphicon-calendar text-primary"></span>
            تاریخ ایجاد
            </strong>
            </td>
            <td class="text-primary">
              {{profile.owner_created_at|to_jalali:'%Y/%m/%d'}}
            </td>
            </tr>
            <tr>
              <td>
              <strong>
              <span class="glyphicon glyphicon-calendar text-primary"></span>
              آخرین بروزرسانی
              </strong>
              </td>
              <td class="text-primary">
                {{profile.owner_updated_at|to_jalali:'%Y/%m/%d'}}
              </td>
              </tr>
    </tbody>
    </table>
    </div>
    </div>

    <div class="container h-100">
        <div class="d-flex h-100">
            <div class="align-self-start mr-auto">
                <a href="{% url 'vdiApp:profileremove' profile_id=profile.owner_user %}">
                    <button type="button" class="btn btn-danger">
                        حذف پروفایل
                    </button>
                </a>
                {%if vd_url %}
                <a href="{{ vd_url }}" target="_blank">
                  <button type="button" class="btn btn-info" >
                      میزکار
                  </button>
              </a>
              {%endif%}
            </div>
        </div>
    </div>

</div>
</div>
    {% endblock %}

vdiManager/templates/vdiApp/serverinfo.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}
{% block contentwraper %}
<h1 class="m-0 text-dark">Server Info</h1>
<hr>
{% endblock%}

{% block maincontent %}
{% if messages %}
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="True">&times;</span>
      </button>
        <h1 ><p style="color: blue">{{ message }}</p></h1>
    </div>
    {% endfor %}
  </div>

</div>
{% endif %}
<div class="content-wraper">
    <h1 name="national_id">Server Name: {{server.server_name }}</h1>
    <hr>
    <h1> Server IP:{{server.server_ip}}</h1>
  
    <div class="container h-100">
        <div class="d-flex h-100">
            <div class="align-self-start mr-auto">
                <a href="{% url 'vdiApp:serverinfo' info_id=server.server_name %}">
                    <button type="button" class="btn btn-info">
                    Status
                    </button>
                </a>
            </div>
        </div>
    </div>

</div>
    {% endblock %}

vdiManager/templates/vdiApp/serverlist.html
{% extends 'base.html' %}
{% load static %}

{% block contentwraper %}
<h1 class="m-0 text-dark">Servers List</h1>
{% endblock%}

{% block maincontent %}

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Path</th>
        <th scope="col">IP</th>
        <th scope="col">Port </th>
        <th scope="col">Scheme</th>
        <th scope="col">Enabled</th>
      </tr>
    </thead>
    <tbody>
      {% for server in servers%}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'vdiApp:serverinfo' info_id=server.server_name %}">{{ server.server_name }}</a></td>
        <td>{{ server.data_path }}</td>
        <td>{{ server.server_ip }}</td>
        <td>{{ server.server_port }}</td>
        <td>{{ server.server_scheme}}</td>
        <td>
          {%if server.is_enabled %}
               <img src="{% static 'assets/img/icon-yes.svg' %}" alt="{{ cert.cert_is_activate }}">
          {%else%}
               <img src="{% static 'assets/img/icon-no.svg' %}" alt="{{ cert.cert_is_activate }}">
          {%endif%}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="text-xs-center">
<nav aria-label="Page navigation example">
<!-- 
      <span class="current">
        Page {{ certs.number }} of {{ certs.paginator.num_pages }}.
      </span> -->

   <ul class="pagination justify-content-center">
      <li class="page-item">
          {% if servers.has_previous %}
          <a class="page-link" aria-label="Previous" href="?page={{ servers.previous_page_number }}">previous</a>
          {% endif %}
          <span class="sr-only">Previous</span>
        
      </li>
      {% for i in servers.paginator.page_range%}
          {%if servers.number == i %}
          <li class="page-item active"><a class="page-link " href="?page={{i}}">{{i}}</a></li>
          {%else%}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {%endif%}
      {%endfor%}
      <li class="page-item">
          {% if servers.has_next %}
          <a class="page-link" aria-label="Next" href="?page={{ vds.next_page_number }}">next</a>
          {% endif %}
          <span class="sr-only">Next</span>
       
      </li>
    </ul> 
</nav>
</div>
{% endblock %}

vdiManager/templates/vdiApp/vdcreate.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block contentwraper %}
<h1 class="m-0 text-dark">ایجاد میزکار</h1>
{% endblock%}

{% block maincontent %}
  <!-- Content Wrapper. Contains page content -->
  {% if messages %}
  <div class="row">
  <div class="col-sm-6 col-sm-offset-3">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
          <h1 ><p style="color: blue">{{ message }}</p></h1>
      </div>
      {% endfor %}
    </div>

  </div>
{% endif %}
    <section class="content">
      <div class="container-fluid">


          <form action="{% url 'vdiApp:vdcreate' %}" method="post">
            {% csrf_token %}
            
            <div class="row ">
                {{ form|bootstrap }}
            </div> 
    <p>{{v}}</p>
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">ایجاد میزکار</button>
  </form>

  
{% endblock %}