vdiManager/accounts/urls.py
from django.urls import path
from .views import login_view,logout_view

app_name = 'accounts'
urlpatterns = [
    path('login/',login_view , name='login'),
    path('logout/',logout_view , name='logout'),

]

vdiManager/adAuth/urls.py
from django.urls import path
from .views import adauth_get_info,adauth_list_info,license_info

app_name = 'adAuth'
urlpatterns = [
    path('',adauth_get_info , name='getinfo'),
    path('license/',license_info , name='licenseinfo'),
    path('authinfo/',adauth_list_info , name='listinfo'),

]

vdiManager/vdiApp/urls.py
from django.urls import path, include
from .views import *

app_name = 'vdiApp'
urlpatterns = [
    path('dashboard/',dashboard , name='dashboard'),
    path('search/',search , name='search'), 
    path('vdcreate/',vdcreate , name='vdcreate'), 
    path('vdlist/',vdlist , name='vdlist'), 
    path('vdremove/<vd_id>',vdremove , name='vdremove'), 
    path('vdinfo/<info_id>',vdinfo , name='vdinfo'),
    path('serverlist/',serverlist , name='serverlist'),
    path('serverinfo/<info_id>',server_info , name='serverinfo'),
    path('profilecreate/',profile_create , name='profilecreate'),
    path('profilelist/',profile_list , name='profilelist'),
    path('profileinfo/<info_id>',profile_info , name='profileinfo'),
    path('profileremove/<profile_id>',profile_remove , name='profileremove'),
    path('profileedit/<profile_id>',profile_edit , name='profileedit'),
    path('profileedit/',profile_edit , name='profileedit'),
    path('api/v1/',include('vdiApp.api.v1.urls')),
]

vdiManager/vdiManager/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vdiApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('adAuth.urls')),
    path('captcha',include("captcha.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vdiManager/templates/base.html
{% load static %}
{% load jalali_tags %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>سامانه تخصیص میزکار مجازی</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'vdi.png' %}"/>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'assets/css/ionicons.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'assets/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Bootstrap 4 RTL -->
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap-v4.2.1.min.css' %}">
  <!-- Custom style for RTL -->
  <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  {% block navbar %}
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <div id="tempMessage" style="display: none; padding: 10px; background-color: #52c6bc; color: #fff; position: fixed; top: 0; left: 50%; transform: translateX(-50%);"></div>
 
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'vdiApp:dashboard' %}" class="nav-link">داشبورد</a>
      </li>
    </ul>
    <form action="{% url 'vdiApp:search' %}" method="GET" class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" id="id_q" type="text" placeholder="جستجو" aria-label="Search" name="q" value="">
      </div>
      

    </form>
    <div>
      <span>ساعت : </span>
      <span style="color:#333333;direction:rtl;margin-right: 10px;" class="date-now">
        {% now "H:i" %}
      </span>
    </div>
    <div style="margin-left:15px"></div>
    <div>
      <span>تاریخ : </span>
      <span style="color:#333333;direction:rtl;margin-right: 10px;" class="date-now">
                {{current_datetime|to_jalali:'%Y/%m/%d'}}           
      </span>
    </div>
    <div style="margin-left:15px"></div>
    <div>
      <span>IP : </span>
      <span style="color:#333333;direction:rtl;margin-right: 10px;" class="date-now">
                {{current_ip}}           
      </span>
    </div>

    <ul class="navbar-nav mr-auto-navbav">

      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{% url 'accounts:logout' %}">
          خروج
        </a>
      </li>

    </ul>
  </nav>
  {% endblock %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% block sidebar %}
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="{% url 'vdiApp:dashboard' %}" class="brand-link">
        <img src="{% static 'assets/img/favicon32.ico' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light"> میزکار مجازی (VDI)</span>
      </a>
  
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <!-- <img src="{% static 'assets/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image"> -->
          </div>
          <div class="info">
            <a href="#" class="d-block">کاربر {% block username %}

              {% if request.user.is_authenticated %}
                {{ request.user.username }}
           
              {% endif %}
           
           {% endblock %}</a>
          </div>
        </div>
  
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview ">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-list"></i>
                <p>
                  میزکار مجازی
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="/vdcreate/" class="nav-link active">
                    <i class="fas fa-edit nav-icon"></i>
                    <p>ایجاد میزکار</p>
                  </a>
                  <li class="nav-item">
                      <a href="/vdlist/" class="nav-link active">
                        <i class="fas fa-list nav-icon"></i>
                        <p>لیست میزکار</p>
                      </a>
                    </li>
                </li>
              </ul>
            </li>
        </nav>
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview ">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-list"></i>
                <p>
                پروفایل ها
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="/profilecreate/" class="nav-link active">
                    <i class="fas fa-edit nav-icon"></i>
                    <p>ایجاد پروفایل</p>
                  </a>
                  <li class="nav-item">
                      <a href="/profilelist/" class="nav-link active">
                        <i class="fas fa-list nav-icon"></i>
                        <p>لیست پروفایل</p>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a href="/profileedit/" class="nav-link active">
                        <i class="fas fa-list nav-icon"></i>
                        <p>ویرایش پروفایل</p>
                      </a>
                    </li>

                </li>
              </ul>
            </li>
        </nav>
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-list"></i>
                <p>
                سرورها
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="/serverlist/" class="nav-link active">
                    <i class="fas fa-edit nav-icon"></i>
                    <p>لیست سرور</p>
                  </a>
                  
                </li>
              </ul>
            </li>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>
  {% endblock %}
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            {% block contentwraper %}
            <h1 class="m-0 text-dark">داشبورد</h1>
            {% endblock%}
            
          </div><!-- /.col -->

        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <!-- /.content-header -->


{% block maincontent  %}
    <h1>Main content</h1>
       
      {% endblock %}
   
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% block footer %}
  <footer class="main-footer">
    <!-- <strong>
        <h6>تمام حقوق این وبگاه متعلق به آستان قدس رضوی است</h6>
    </strong> -->
    
 
  </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
      </aside>
      <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- <script>
      $.widget.bridge('uibutton', $.ui.button)
    </script> -->
    <!-- Bootstrap 4 rtl -->
    <script src="{% static 'assets/js/bootstrap-v4.2.1.min.js' %}"></script>


    <!-- AdminLTE App -->
    <script src="{% static 'assets/js/adminlte.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <!-- <script src="{% static 'assets/js/pages/dashboard.js' %}"></script> -->
    <!-- AdminLTE for demo purposes -->
    <!-- <script src="{% static 'assets/js/demo.js' %}"></script> -->
    {% endblock %}

    <script src="{% static 'assets/js/copytext.js'  %}" type="text/javascript"></script>
</body>
</html>